### ISSUE TITLE
Regression for testing in Hanami 0.1.1

### ISSUE THREAD

**Issue by mrship** [hanami/api#15]
We can't run more than one rspec test under Hanami 0.1.1, whereas we can under 0.1.0.

With a test script (outlined at the bottom of the issue) under 0.1.1, we get the following failure:

```bash
rspec hanami_fail_spec.rb
/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:136: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
.F

Failures:

  1) Web ping endpoint returns 200
     Failure/Error: Web.new

     NoMethodError:
       undefined method `finalize' for nil:NilClass
     # ./hanami_fail_spec.rb:26:in `new'
     # ./hanami_fail_spec.rb:26:in `app'
     # ./hanami_fail_spec.rb:37:in `block (3 levels) in <top (required)>'

Finished in 0.00754 seconds (files took 0.23851 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./hanami_fail_spec.rb:36 # Web ping endpoint returns 200
```

Running individual tests works fine:

```
rspec hanami_fail_spec.rb:36
/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:136: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
Run options: include {:locations=>{"./hanami_fail_spec.rb"=>[36]}}
.

Finished in 0.00585 seconds (files took 0.23999 seconds to load)
1 example, 0 failures
```

---

Under Hanami API 0.1.0, both specs run (and succeed).

```bash
rspec hanami_fail_spec.rb
/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.0/lib/hanami/api/block/context.rb:130: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
..

Finished in 0.00771 seconds (files took 0.23655 seconds to load)
2 examples, 0 failures
```

---

Test script:

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  ruby '2.7.1'

  gem 'hanami-api', '0.1.1' # change this to '0.1.0' to succeed.
  gem 'rack-test'
  gem 'rspec'
end

require 'hanami/api'

class Web < Hanami::API
  get "/ping" do
    "pong"
  end
end

RSpec.describe Web do
  include Rack::Test::Methods

  def app
    Web.new
  end

  describe "ping endpoint" do
    it "returns pong" do
      get "/ping"

      expect(last_response.body).to eq "pong"
    end

    it "returns 200" do
      get "/ping"

      expect(last_response.status).to eq 200
    end
  end
end
```

**Comment by jodosha** [comment]
@mrship I can reproduce the bug. Sorry about this problem. Will look into this soon.

**Comment by jodosha** [comment]
@mrship Could you please check if #16 fixes the problem for you? I pointed your test script to the branch and it works for me.

```ruby
gem "hanami-api", git: "https://github.com/hanami/api.git", branch: "fix/ensure-to-instantiate-app-multiple-times"
```

**Comment by mrship** [comment]
@jodosha Yes, your fix branch works for me - thanks!
