### ISSUE TITLE
retrieve client ip address (source ip)

### ISSUE THREAD

**Issue by KINGSABRI** [hanami/api#17]
Hi folks 
First of all, I would like to thank you for all the efforts you spent on hanami. 

I'm writing a very basic API and I want to retrieve the requester's IP address (client IP address). I've tried `request.ip` but it didn't work hence the rack server stops running.

```ruby
require "bundler/setup"
require "hanami/api"
require "hanami/middleware/body_parser"


class App < Hanami::API
  use Hanami::Middleware::BodyParser, :json

  get "/" do
    "Thank you for visiting us.."
  end

  post "/" do
    "Thank you for visiting us.."
  end
end

run App.new
```

Thank you

**Comment by jodosha** [comment]
@KINGSABRI Hey, what does happen exactly? Do you have more details to share? Something like a stack-trace. Thanks in advance.

**Comment by KINGSABRI** [comment]
Hi @jodosha 

Here is my code 

```ruby
# frozen_string_literal: true
require "bundler/setup"
require "hanami/api"
require "hanami/middleware/body_parser"

class App < Hanami::API
  use Hanami::Middleware::BodyParser, :json

  get "/" do
    puts request.ip
    "Thank you for visiting us.."
  end

  post "/" do
    "Thank you for visiting us.."
  end
end

run App.new
```
Here is the backtrace 
```
NameError: undefined local variable or method `request' for #<Hanami::API::Block::Context:0x00007f8716a0a8f8>
Did you mean?  require
	/Users/MyUserName/Code/collector-api/config.ru:11:in `block in <class:App>'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:166:in `instance_exec'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:166:in `block in caught'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:165:in `catch'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:165:in `caught'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/block/context.rb:136:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-router-2.0.0.alpha3/lib/hanami/router/block.rb:84:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-router-2.0.0.alpha3/lib/hanami/router.rb:92:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-router-2.0.0.alpha3/lib/hanami/middleware/body_parser.rb:43:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api/middleware/app.rb:36:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:315:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/Users/MyUserName/.rbenv/versions/2.7.1/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by jodosha** [comment]
@KINGSABRI That's simply because `request` isn't implemented.

The reason why it isn't implemented yet it's because `Rack::Request` is a heavy object that drags down perf (according to my benchmarks).

You can access Rack Env via `env` and from there you can construct your own `Rack::Request.new(env)`.

---

Here's the methods that are available in the block:

  * https://github.com/hanami/router/blob/unstable/lib/hanami/router/block.rb
  * https://github.com/hanami/api/blob/master/lib/hanami/api/block/context.rb

---

As long term solution I want people to be able to customize the block execution and to implement their own utilities (like `request` method).
