### ISSUE TITLE
Scope without leading slash doesn't work with Rack middlewares

### ISSUE THREAD

**Issue by k0va1** [hanami/api#8]
@jodosha hey. Here is an example. Let me know if you need more information
```ruby
class SimpleMid
  def initialize(app)
    @app = app
  end

  def call(env)
    puts 'hello'
    @app.call(env)
  end
end

class App < Hanami::API
  scope 'admin' do # scope doesn't have leading `/`
    use SimpleMid # middleware is in use
    root to: lambda { |env|
      body = "body"
      [200, { "Content-Length" => body.bytesize }, [body]]
    }
  end 
end
```
```bash 
curl -i -X GET http://localhost:9292/admin
```
Stacktrace:
```
ArgumentError: paths need to start with /
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:34:in `block in remap'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:25:in `each'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:25:in `map'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:25:in `remap'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:20:in `initialize'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:254:in `new'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:254:in `generate_map'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:232:in `to_app'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:244:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/hanami-api-0.1.0/lib/hanami/api.rb:326:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:50:in `_call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:38:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/show_exceptions.rb:23:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/common_logger.rb:38:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/home/k0va1/.asdf/installs/ruby/2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```
Scope with trailing slash works fine. Something like `scope '/admin' do...`. It also works fine with `scope 'admin' do...` but **without** middleware. 

I don't know is it a bug or Rack just works like this

**Comment by jodosha** [comment]
@k0va1 Sorry for the long wait. Could you please try if #9 fixes your problem? Thanks.

**Comment by jodosha** [comment]
A bit of explanation: scope names are used as path prefixes for routes that are evaluated in their block. The internal router handles the lack of leading slash, but the middleware stack (`Rack::Builder`) doesn't.
